### PR TITLE
Run all tests, not just find flags

### PR DESCRIPTION
**Pull request by JordanMartinez**
### Description of the change

TODO

### Checklist:

- [ ] Added the change to the "Unreleased" section of the changelog
- [ ] Added some example of the new feature to the `README`
- [ ] Added a test for the contribution (if applicable)

**P.S.**: the above checks are not compulsory to get a change merged, so you may skip them. However, taking care of them will result in less work for the maintainers and will be much appreciated 😊

### CODE REVIEW

**Comment by JordanMartinez** [comment]
The `run > works at all` test keeps timing out in various PRs. I'm wondering what's going on there...

**Comment by f-f** [comment]
I wonder if we should update to the latest package set since there might be execa or node bugs in this one?

**Comment by JordanMartinez** [comment]
Quite possibly. But that requires updating the Registry as well. I already started looking down this path.

**Comment by f-f** [comment]
We are already pointing to the latest commit of the registry-dev repo if that's what you are referring to

**Comment by f-f** [comment]
I hate this windows build, rerunning..

**Comment by f-f** [comment]
@JordanMartinez is this PR still relevant?

**Pull request closed without merging**
