### PR TITLE
test: spago docs

### PR DESCRIPTION
**Pull request by CharlesTaylor7**
Just a follow up to #1025, and this request for more test assertions: https://github.com/purescript/spago/pull/1025#discussion_r1341015507

### CODE REVIEW

**Review by JordanMartinez — APPROVED** [review]

**Review by f-f — APPROVED** [review]
Lovely, thanks!

**Comment by f-f** [comment]
@CharlesTaylor7 could you merge in the latest? GitHub doesn't give me a button to bump it as usual 🤔

**Comment by CharlesTaylor7** [comment]
Oh... i think its because I unchecked " allow edits from maintainers" when creating the PR. I re-enabled that.

**Comment by f-f** [comment]
Ah I see - thanks!

**Pull request merged**
