### PR TITLE
🎅 Fetch before rebuild

### PR DESCRIPTION
**Pull request by flip111**
Fix https://github.com/purescript/spago/issues/1110

### CODE REVIEW

**Comment by f-f** [comment]
I don't think this is fixing the issue - the dependencies from the build plan are not passed in anywhere, and these are the ones we need to fetch.

A good first step for a fix would be to write a test that replicates the issue in #1110. After we get CI to fail because of that we can then write the correct patch.

**Comment by flip111** [comment]
I'm not a fan of ttd i rather write the patch first if i go ahead with this. Should `Fetch.run` called multiple times for each dependency or can i pass all the deps at once?

**Comment by f-f** [comment]
This is not about TTD, but rather about replicating the failure in a standard environment (CI). If we can't replicate we can't fix.

**Comment by flip111** [comment]
Can the registry be queried as to what is the latest version of a package?

**Comment by f-f** [comment]
Why would we need that? We'll need to build with whatever versions the solver returns, which is not always going to be the latest one.

**Comment by flip111** [comment]
As new versions get added to the registry, the solver might resolve to something else. I expect the test to start breaking.

**Comment by f-f** [comment]
> I expect the test to start breaking.

It's entirely possible to have a test that doesn't break over time - we'll need to set the version bounds to be different than what the package set contains.

**Comment by flip111** [comment]
In #1110 i don't think it was relevant that an outdated package `0.4.1` was available in the cache. The problem should just reproduce when removing any package from the cache which then should be refetched before rebuild. That the problem occurs due to an upgraded version of a dependency is not relevant to test the solution.

**Comment by flip111** [comment]
The test passes but i don't think it works correctly. Not sure what is happening

**Comment by f-f** [comment]
This has been discussed on Discord, but I'll report here as well:
Spago uses a global cache and I think that's ultimately the reason why the new test is not working - you are deleting the package from the local cache, but Spago will find it in the global cache so it just copies it back there.
The user-facing command to get the location of the global cache is `spago ls paths`, but in tests you can use the `Spago.Paths` module

**Comment by flip111** [comment]
Superseed by https://github.com/purescript/spago/pull/1283

**Pull request closed without merging**
