### PR TITLE
Allow upgrade of alternative package sets

### PR DESCRIPTION
**Pull request by nwolverson**
### Description of the change

Allow upgrade via `spago upgrade-set` when the package set is other than `purescript/package-sets`.

Motivation:
* Alternate backends which use an alternative package set (https://github.com/purerl/package-sets)
* Organisation-private package sets

### Checklist:

- [x] Added the change to the "Unreleased" section of the changelog
- [ ] Added some example of the new feature to the `README`
- [x] Added a test for the contribution (if applicable)

**P.S.**: the above checks are not compulsory to get a change merged, so you may skip them. However, taking care of them will result in less work for the maintainers and will be much appreciated 😊

### CODE REVIEW

**Comment by nwolverson** [comment]
Thanks, I'll add it to the changelog - couldn't think of a straightforward way of adding a test as the non-alt version uses `init` which of course sets up for the wrong repo

**Comment by f-f** [comment]
You mean that it points to the default package set? In tests we already [point to a custom release](https://github.com/purescript/spago/blob/357dcbd9fc023b9a4fc3282263bbc0e7c6af7c56/test/SpagoSpec.hs#L574), so I guess you could point to a release of the Erlang package set and test it? Or am I missing something?

**Comment by nwolverson** [comment]
If I understand that test, it does an init which sets packages.dhall to point to the current release, overwrites that with a specific old release, does an upgrade, and checks that it is back in the starting position, ie the current release. What I could do is check that after upgrading it *has changed*, which I didn't think of when I wrote the earlier comment, but not that it is at the current release (without embedding that in the test).

**Comment by f-f** [comment]
@nwolverson oh that's right, what you propose sounds great to me :+1:

**Pull request merged**
