### PR TITLE
Add support of es modules branch

### PR DESCRIPTION
**Pull request by sigma-andex**
### Description of the change

Draft pr for #836 using esbuild as bundler to get the discussion started. 

### Checklist:

- [ ] Added the change to the "Unreleased" section of the changelog
- [ ] Added some example of the new feature to the `README`
- [ ] Added a test for the contribution (if applicable)

**P.S.**: the above checks are not compulsory to get a change merged, so you may skip them. However, taking care of them will result in less work for the maintainers and will be much appreciated 😊

### CODE REVIEW

**Comment by f-f** [comment]
@sigma-andex what's the status of this? I see this is not a draft anymore, but would you like to actually have it merged right now?

I'm not sure we would merge any breaking change of this sort until changes to the bundle logic in the compiler are released, and even then we would still support the `bundle` commands as they are for earlier compilers.
My understanding is that this patch exists to make the es-module work move forward, but I'm not sure it should even be a pull request yet?

**Comment by sigma-andex** [comment]
No, not yet merged of course until this is coordinated with the v0.15 release. 
But it would be great to get some feedback/review on this.

**Comment by i-am-the-slime** [comment]
@f-f I think it would be nice if the maintainers (you? 😁 ) could give their input on whether this needs changes or it could be merged in concert with the 0.15 release. 
I think it makes sense to get some PRs ready and publicise this early on rather than it just happening inside the obscure es-modules-working-group org.
 
If you prefer for it to stay a draft that's fine too, of course.

**Comment by sigma-andex** [comment]
@f-f regarding the backwards compatibility: I can have a look at this. I think that shouldn't be a problem if the version information is available somewhere

**Comment by sigma-andex** [comment]
Closing this in favour of #862

**Pull request closed without merging**
