### PR TITLE
Handle absolute config paths

### LINKED ISSUE #472: --config option doesnt accept absolute path
if you do

```
YOUR_PROJECT_DIR_FULLPATH=$HOME/example
YOUR_PROJECT_DIR_RELATIVE_PATH=example
cd $SOME_OTHER_DIR
```

then 

```
$ spago --config $YOUR_PROJECT_DIR_FULLPATH/spago.dhall list-packages --filter transitive --json
spago:
Error: Invalid input

(input):1:3:
  |
1 | .//home/srghma/projects/spago2nix/spago.dhall
  |   ^
unexpected '/'
expecting expression or whitespace
```

and 

```
$ spago --config $YOUR_PROJECT_DIR_RELATIVE_PATH/spago.dhall list-packages --filter transitive --json
↳ ./packages.dhall

Error: Missing file ./packages.dhall

21│     ./packages.dhall

21:5
```

_______

real example

```
[nix-shell:~/projects]$ spago --config $HOME/projects/spago2nix/spago.dhall list-packages --filter transitive --json
spago:
Error: Invalid input

(input):1:3:
  |
1 | .//home/srghma/projects/spago2nix/spago.dhall
  |   ^
unexpected '/'
expecting expression or whitespace


[nix-shell:~/projects]$ spago --config spago2nix/spago.dhall list-packages --filter transitive --json
spago:
↳ ./packages.dhall

Error: Missing file ./packages.dhall

21│     ./packages.dhall

21:5

[nix-shell:~/projects]$
````

_____

the second error `Missing file ./packages.dhall` is a bit different, I believe that path should be derived from `spago.dhall` `packages` option

```
{-
Welcome to a Spago project!
You can edit this file as you like.
-}
{ sources =
    [ "src/**/*.purs", "test/**/*.purs" ]
, name =
    "my-project"
, dependencies =
    [ "console"
    , "generics-rep"
    , "kishimen"
    , "node-fs-aff"
    , "parallel"
    , "prelude"
    , "simple-json-utils"
    , "sunde"
    , "validation"
    ]
, packages =
    ./packages.dhall
}
```

### PR DESCRIPTION
**Pull request by elliotdavies**
### Description of the change

Replaces #485 as a fix for #472, and tidies up a few things.

Fix #472

### Checklist:

- [x] Added the change to the "Unreleased" section of the changelog
- [ ] ~Added some example of the new feature to the `README`~
- [x] Added a test for the contribution (if applicable)

**P.S.**: the above checks are not compulsory to get a change merged, so you may skip them. However, taking care of them will result in less work for the maintainers and will be much appreciated 😊

### CODE REVIEW

**Comment by f-f** [comment]
Update: it looks something is up with the Windows tests

**Comment by elliotdavies** [comment]
@f-f Oh of course, because of the absolute paths on Windows... 🙈 I guess we'll have to do without for now?

**Comment by elliotdavies** [comment]
The tests are continuing to fail on Windows because I switched to using `Dhall.Import.localToPath` which returns an OS-specific path, but our test fixtures hard-code the Unix versions. @f-f do you know if it would be difficult to use a different text fixture on Windows, or something similar?

**Comment by f-f** [comment]
@elliotdavies yes, we can `case` on the OS, as we do already e.g. here:
https://github.com/spacchetti/spago/blob/a4679880402ead320f8be2f091b25d30e27b62df/src/Spago/Bower.hs#L142-L146

**Comment by elliotdavies** [comment]
(I'm kind of blocked on this without a Windows machine of my own to test on. The fixtures certainly need updating but some of the other tests are failing too and I'm not certain why.)

**Comment by toastal** [comment]
Any updates on this? I want to use process substitution to create files on the fly, but I can't because of the `.//tmp/absolute/directiory/spago.dhall` issue.

**Pull request closed without merging**
