### PR TITLE
Update links: spacchetti/spago → purescript/spago

### PR DESCRIPTION
**Pull request by f-f**

### CODE REVIEW

**Comment by klntsky** [comment]
You forgot the .cabal file and README.

**Comment by f-f** [comment]
@klntsky the cabal file is not versioned (it is [gitignored in fact](https://github.com/purescript/spago/blob/cc755561d992406533e0ca1fd2fe4087c047a7bb/.gitignore#L4))

**Comment by klntsky** [comment]
Oops, you are right, I grep'd in my local files.

**Comment by f-f** [comment]
Closing until #423 gets sorted out

**Pull request merged**
