### PR TITLE
Add '--' after node eval and before node args

### LINKED ISSUE #855: `spago run -a '--someFlag'` fails to run
Reproducible example:
```sh
mkdir bug
cd bug
spago init
# this works
spago run -a "flagName"
# this doesn't due to the '--' usage
spago run -a "--flagName"
```

This bug was introduced in `v0.20.4`, likely in #846 at [this line](https://github.com/purescript/spago/pull/846/files#diff-39f237ba9dc724f764aeae78cda0509364f4ff15174b5b88ae34159dba5e05acR344), which executes

`node -e "scriptContent" --flagName`
rather than
`node -e "scriptContent" -- --flagName`

For example:
```sh
$ node -e "console.log(process.argv);" --bar
node: bad option: --bar
$ node -e "console.log(process.argv);" -- --bar
[ '/home/jordan/.nvm/versions/node/v16.13.0/bin/node', '--bar' ]
```

### PR DESCRIPTION
**Pull request by JordanMartinez**
### Description of the change

Fixes #855 

### Checklist:

- [x] Added the change to the "Unreleased" section of the changelog
- [ ] Added some example of the new feature to the `README`
- [x] Added a test for the contribution (if applicable)

**P.S.**: the above checks are not compulsory to get a change merged, so you may skip them. However, taking care of them will result in less work for the maintainers and will be much appreciated 😊

### CODE REVIEW

**Review by f-f — APPROVED** [review]
Looks great, thanks!

If you bump the release number in `spago.cabal` and in the Changelog we can also release this right away :slightly_smiling_face:

**Comment by f-f** [comment]
Thank you! I won't be at a computer for a while, so it'd be great if any of you could run the `./release.sh` script to get the release out

**Comment by JordanMartinez** [comment]
I just ran `./release.sh`.

**Comment by f-f** [comment]
You ran that on your fork, it needs to be run from this repo - IIRC you should be authorised to push to the repo, but if not I can fix this next time I'm at a keyboard

**Pull request merged**
