### PR TITLE
Override a package in the package set with a remote one: dependencies

### PR DESCRIPTION
**Pull request by flip111**

### CODE REVIEW

**Comment by f-f** [comment]
I'm a little concerned about giving out the idea that all three keys are needed in order to override something, do you think we could move this to some other place?

**Comment by flip111** [comment]
the idea comes from spago itself, seems right to document it

```
[error] Failed to read the config. Error was:
[error] Error: Error while reading spago.dhall:

Explanation: a record is missing a required key.

The key missing is:

↳ dependencies

The keys in the record are:

↳ repo, version
```

**Comment by f-f** [comment]
Oh, but that's the case when you add a new package (which is documented in the next section), this section deals with overriding an existing package

**Comment by flip111** [comment]
Thought package already existed. Don't really understand why i had to copy paste dependencies ?

https://github.com/natefaubion/purescript-tidy-codegen/blob/main/spago.dhall#L14-L56

**Comment by f-f** [comment]
It's for historical reasons - we couldn't/didn't want to read them from Bower files when creating the package set. This is going to change once the new [Registry](https://github.com/purescript/registry) is live

**Comment by flip111** [comment]
ok let's close this for now, registry sounds promising !

**Pull request closed without merging**
