### PR TITLE
fix `cabal build --enable-tests`, update Stack resolver, fix Spago on Nixpkgs

### PR DESCRIPTION
**Pull request by peterbecich**
### Description of the change

Closes: https://github.com/purescript/spago/issues/987

- Fix `cabal build --enable-tests`

- Tested with same GHC as in Stack resolver, 9.2

- Update Stack resolver to latest for GHC 9.2

- Basic GitHub Action for Cabal, copied from: https://github.com/haskell/actions/tree/main/setup#model-cabal-workflow-with-caching

- Fix compatibility with latest FSNotify (https://hackage.haskell.org/package/fsnotify-0.4.1.0/docs/System-FSNotify.html), which should fix Spago on Nixpkgs: https://github.com/NixOS/nixpkgs/issues/253198
  - debounce was removed from library: https://hackage.haskell.org/package/fsnotify-0.4.1.0/changelog

### Checklist:

- [x] Added the change to the "Unreleased" section of the changelog
- [ ] Added some example of the new feature to the `README`
- [ ] Added a test for the contribution (if applicable)

**P.S.**: the above checks are not compulsory to get a change merged, so you may skip them. However, taking care of them will result in less work for the maintainers and will be much appreciated 😊

### CODE REVIEW

**Comment by f-f** [comment]
Thanks @peterbecich! This looks good, but do we need the new action with the cabal build? The expected dev setup uses stack and I'm not interested in supporting other things at the moment

**Comment by peterbecich** [comment]
@f-f thanks, would it be adequate to make the Cabal build "failure allowed" and remove the badge from the readme?
Happy to remove entirely, up to you of course.

**Comment by f-f** [comment]
Actually nvm, let's just leave it in - I am about to switch out all of these workflows anyways, since the next version of Spago is written in PureScript and we need to start compiling that in CI.

**Review by f-f — APPROVED** [review]

**Comment by f-f** [comment]
Thanks @peterbecich!

**Pull request merged**
