### PR TITLE
Integrate PSA into codebase

### LINKED ISSUE #904: Integrate psa into Spago
Since the upcoming Spago will be in PureScript, we now have the occasion of integrating `psa` directly [as a library](https://github.com/natefaubion/purescript-psa-utils), which is strictly better than the current situation of shelling out to an external executable.

### PR DESCRIPTION
**Pull request by JordanMartinez**
### Description of the change

Fixes #904. Currently a WIP.

### Checklist:

- [ ] Added the change to the "Unreleased" section of the changelog
- [ ] Added some example of the new feature to the `README`
- [ ] Added a test for the contribution (if applicable)

**P.S.**: the above checks are not compulsory to get a change merged, so you may skip them. However, taking care of them will result in less work for the maintainers and will be much appreciated 😊

### CODE REVIEW

**Comment by JordanMartinez** [comment]
Feel free to provide any feedback while I work on this. For example:
- should `flag` args always have a `ArgParser.boolean x` to be explicit about what the default is? Or do we defer to the defaults provided by `ArgParser` (currently `false`)?
- where should I place constant values (e.g. `.psa-stash`)?
- is prefixing all `psa` args with `psa` ok? Or should that be handled differently?

**Comment by f-f** [comment]
Thanks for picking this up!

> should flag args always have a `ArgParser.boolean x` to be explicit about what the default is? 

I don't have an opinion on this and providing defaults might be sensible for certain things and less sensible for others, but in any case keep in mind that for some/all the flags we should also offer the possibility to configure them from the config file. See e.g. how this is done for `bundle`'s arguments:

https://github.com/purescript/spago/blob/2cb7edfe12c6751e94d1ad6f193b1b4f9e112398/spaghetto/bin/src/Main.purs#L246-L254

> where should I place constant values (e.g. `.psa-stash`)?

Are you looking for a place to stash files? The `.spago` folder is there for that, feel free to make a subdirectory `.spago/psa` if you need to store more stuff.

> is prefixing all `psa` args with `psa` ok? Or should that be handled differently?

Definitely ok to have this prefix in the source, and we might want to even prefix some/all the flags with `psa`, so that it's clear that they control psa's behaviour

**Comment by JordanMartinez** [comment]
> Are you looking for a place to stash files? The .spago folder is there for that, feel free to make a subdirectory .spago/psa if you need to store more stuff.

How about we have a special `spago-specific` directory that's easily accessible (in that it appear above all the other dependency folders)? For example `.spago/_internal/psa/<stash file>`. This could also store the `.spago/_internal/run.js` file. Otherwise, if I want to look at the stash file, I may have to scroll through a large number of dependency folders before I see the `psa` folder.

**Comment by f-f** [comment]
> I may have to scroll through a large number of dependency folders before I see the psa folder.

I've been very annoyed by this in the past too, which is why spaghetto stores packages in `.spago/packages` 🙂

**Comment by JordanMartinez** [comment]
Succeeded by #955

**Pull request closed without merging**
